[package]
name = "dummy"
version = "0.1.0"
authors = ["Miro Svrtan <miro@mirosvrtan.me>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
askama ={ version = "0.8", features = ["with-rocket"] }

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = []
